### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no tdjni in java.library.path

### ISSUE THREAD

**Issue by yvasyliev** [tdlight-team/tdlight-java#156]
Hi, my app built with TdLight fails at runtime with the following console output:
```
C:\Users\Yevhen\.jdks\corretto-17.0.7\bin\java.exe "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2023.1.1\lib\idea_rt.jar=52795:C:\Program Files\JetBrains\IntelliJ IDEA 2023.1.1\bin" -Dfile.encoding=UTF-8 -classpath C:\Users\Yevhen\IdeaProjects\telegram-dynamic-profile-photo\target\classes;C:\Users\Yevhen\.m2\repository\com\github\yvasyliev\deezer-api\2.1.0\deezer-api-2.1.0.jar;C:\Users\Yevhen\.m2\repository\org\slf4j\slf4j-api\2.0.6\slf4j-api-2.0.6.jar;C:\Users\Yevhen\.m2\repository\com\google\code\gson\gson\2.10.1\gson-2.10.1.jar;C:\Users\Yevhen\.m2\repository\com\squareup\okhttp3\okhttp\4.10.0\okhttp-4.10.0.jar;C:\Users\Yevhen\.m2\repository\com\squareup\okio\okio-jvm\3.0.0\okio-jvm-3.0.0.jar;C:\Users\Yevhen\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib-jdk8\1.5.31\kotlin-stdlib-jdk8-1.5.31.jar;C:\Users\Yevhen\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib-jdk7\1.5.31\kotlin-stdlib-jdk7-1.5.31.jar;C:\Users\Yevhen\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib-common\1.5.31\kotlin-stdlib-common-1.5.31.jar;C:\Users\Yevhen\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib\1.6.20\kotlin-stdlib-1.6.20.jar;C:\Users\Yevhen\.m2\repository\org\jetbrains\annotations\13.0\annotations-13.0.jar;C:\Users\Yevhen\.m2\repository\it\tdlight\tdlight-java\3.0.6+td.1.8.14\tdlight-java-3.0.6+td.1.8.14.jar;C:\Users\Yevhen\.m2\repository\org\reactivestreams\reactive-streams\1.0.4\reactive-streams-1.0.4.jar;C:\Users\Yevhen\.m2\repository\io\atlassian\util\concurrent\atlassian-util-concurrent\4.0.1\atlassian-util-concurrent-4.0.1.jar;C:\Users\Yevhen\.m2\repository\it\tdlight\tdlight-api\4.0.392\tdlight-api-4.0.392-legacy.jar;C:\Users\Yevhen\.m2\repository\it\tdlight\tdlight-api\4.0.392\tdlight-api-4.0.392.jar;C:\Users\Yevhen\.m2\repository\it\tdlight\tdlight-natives\4.0.422\tdlight-natives-4.0.422-linux_amd64_ssl1.jar;C:\Users\Yevhen\.m2\repository\it\tdlight\tdlight-natives\4.0.422\tdlight-natives-4.0.422-windows_amd64.jar;C:\Users\Yevhen\.m2\repository\org\apache\logging\log4j\log4j-slf4j2-impl\2.20.0\log4j-slf4j2-impl-2.20.0.jar;C:\Users\Yevhen\.m2\repository\org\apache\logging\log4j\log4j-api\2.20.0\log4j-api-2.20.0.jar;C:\Users\Yevhen\.m2\repository\org\apache\logging\log4j\log4j-core\2.20.0\log4j-core-2.20.0.jar;C:\Users\Yevhen\.m2\repository\org\springframework\spring-context\6.0.9\spring-context-6.0.9.jar;C:\Users\Yevhen\.m2\repository\org\springframework\spring-aop\6.0.9\spring-aop-6.0.9.jar;C:\Users\Yevhen\.m2\repository\org\springframework\spring-beans\6.0.9\spring-beans-6.0.9.jar;C:\Users\Yevhen\.m2\repository\org\springframework\spring-core\6.0.9\spring-core-6.0.9.jar;C:\Users\Yevhen\.m2\repository\org\springframework\spring-jcl\6.0.9\spring-jcl-6.0.9.jar;C:\Users\Yevhen\.m2\repository\org\springframework\spring-expression\6.0.9\spring-expression-6.0.9.jar app.telegram.Main telegram.update_photo
14:44:07.463 [main] ERROR app.telegram.Main - Failed to execute command: telegram.update_photo
it.tdlight.util.UnsupportedNativeLibraryException: Failed to load TDLight native libraries
	at it.tdlight.util.Native.loadLibrary(Native.java:62) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
	at it.tdlight.util.Native.loadNativesInternal(Native.java:37) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
	at it.tdlight.Init.init(Init.java:53) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
	at app.telegram.Main.main(Main.java:33) [classes/:?]
Caused by: java.lang.IllegalArgumentException: Failed to load any of the given libraries: [tdjni.windows_amd64]
	at it.tdlight.util.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:130) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
	at it.tdlight.util.Native.loadLibrary(Native.java:55) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
	... 3 more
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: tdjni.windows_amd64
		at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:255) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
		at it.tdlight.util.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:121) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
		at it.tdlight.util.Native.loadLibrary(Native.java:55) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
		at it.tdlight.util.Native.loadNativesInternal(Native.java:37) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
		at it.tdlight.Init.init(Init.java:53) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
		at app.telegram.Main.main(Main.java:33) [classes/:?]
	Caused by: java.io.FileNotFoundException: META-INF/tdlightjni/tdjni.windows_amd64.dll
		at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:202) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
		... 5 more
		Suppressed: java.lang.UnsatisfiedLinkError: no tdjni.windows_amd64 in java.library.path: C:\Users\Yevhen\.jdks\corretto-17.0.7\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Users\Yevhen\.jdks\corretto-17.0.7\bin;C:\Users\Yevhen\IdeaProjects\telegram-dynamic-profile-photo\libs;C:\Users\Yevhen\AppData\Local\Microsoft\WindowsApps;;.
			at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429) ~[?:?]
			at java.lang.Runtime.loadLibrary0(Runtime.java:818) ~[?:?]
			at java.lang.System.loadLibrary(System.java:1989) ~[?:?]
			at it.tdlight.util.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:23) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
			at it.tdlight.util.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:433) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
			at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:177) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
			at it.tdlight.util.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:121) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
			at it.tdlight.util.Native.loadLibrary(Native.java:55) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
			at it.tdlight.util.Native.loadNativesInternal(Native.java:37) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
			at it.tdlight.Init.init(Init.java:53) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
			at app.telegram.Main.main(Main.java:33) [classes/:?]
			Suppressed: java.lang.UnsatisfiedLinkError: no tdjni.windows_amd64 in java.library.path: C:\Users\Yevhen\.jdks\corretto-17.0.7\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Users\Yevhen\.jdks\corretto-17.0.7\bin;C:\Users\Yevhen\IdeaProjects\telegram-dynamic-profile-photo\libs;C:\Users\Yevhen\AppData\Local\Microsoft\WindowsApps;;.
				at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429) ~[?:?]
				at java.lang.Runtime.loadLibrary0(Runtime.java:818) ~[?:?]
				at java.lang.System.loadLibrary(System.java:1989) ~[?:?]
				at it.tdlight.util.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:23) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
				at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
				at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
				at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
				at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
				at it.tdlight.util.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:462) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
				at it.tdlight.util.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:425) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
				at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:177) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
				at it.tdlight.util.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:121) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
				at it.tdlight.util.Native.loadLibrary(Native.java:55) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
				at it.tdlight.util.Native.loadNativesInternal(Native.java:37) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
				at it.tdlight.Init.init(Init.java:53) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
				at app.telegram.Main.main(Main.java:33) [classes/:?]
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: tdjni
		at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:255) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
		at it.tdlight.util.Native.loadLibrary(Native.java:58) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
		at it.tdlight.util.Native.loadNativesInternal(Native.java:37) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
		at it.tdlight.Init.init(Init.java:53) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
		at app.telegram.Main.main(Main.java:33) [classes/:?]
	Caused by: java.io.FileNotFoundException: META-INF/tdlightjni/tdjni.dll
		at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:202) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
		... 4 more
		Suppressed: java.lang.UnsatisfiedLinkError: no tdjni in java.library.path: C:\Users\Yevhen\.jdks\corretto-17.0.7\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Users\Yevhen\.jdks\corretto-17.0.7\bin;C:\Users\Yevhen\IdeaProjects\telegram-dynamic-profile-photo\libs;C:\Users\Yevhen\AppData\Local\Microsoft\WindowsApps;;.
			at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429) ~[?:?]
			at java.lang.Runtime.loadLibrary0(Runtime.java:818) ~[?:?]
			at java.lang.System.loadLibrary(System.java:1989) ~[?:?]
			at it.tdlight.util.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:23) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
			at it.tdlight.util.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:433) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
			at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:177) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
			at it.tdlight.util.Native.loadLibrary(Native.java:58) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
			at it.tdlight.util.Native.loadNativesInternal(Native.java:37) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
			at it.tdlight.Init.init(Init.java:53) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
			at app.telegram.Main.main(Main.java:33) [classes/:?]
			Suppressed: java.lang.UnsatisfiedLinkError: no tdjni in java.library.path: C:\Users\Yevhen\.jdks\corretto-17.0.7\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Users\Yevhen\.jdks\corretto-17.0.7\bin;C:\Users\Yevhen\IdeaProjects\telegram-dynamic-profile-photo\libs;C:\Users\Yevhen\AppData\Local\Microsoft\WindowsApps;;.
				at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429) ~[?:?]
				at java.lang.Runtime.loadLibrary0(Runtime.java:818) ~[?:?]
				at java.lang.System.loadLibrary(System.java:1989) ~[?:?]
				at it.tdlight.util.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:23) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
				at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
				at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
				at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
				at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
				at it.tdlight.util.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:462) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
				at it.tdlight.util.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:425) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
				at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:177) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
				at it.tdlight.util.Native.loadLibrary(Native.java:58) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
				at it.tdlight.util.Native.loadNativesInternal(Native.java:37) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
				at it.tdlight.Init.init(Init.java:53) ~[tdlight-java-3.0.6+td.1.8.14.jar:?]
				at app.telegram.Main.main(Main.java:33) [classes/:?]

Process finished with exit code 1
```

This worked OK with TdLight v2.
[Project source](https://github.com/yvasyliev/telegram-dynamic-profile-photo/tree/tdlight_v3)

---
OS: Windows 11
TdLight: 3.0.6+td.1.8.14

**Comment by cavallium** [comment]
Fixed in https://github.com/tdlight-team/tdlight-java/releases/tag/v3.0.7%2Btd.1.8.14

**Comment by sspotanin** [comment]
@cavallium still have this issue on windows at [v3.0.7%2Btd.1.8.14](https://github.com/tdlight-team/tdlight-java/releases/tag/v3.0.7%2Btd.1.8.14)

**Comment by cavallium** [comment]
3.0.8 fixed it

**Comment by cavallium** [comment]
@sspotanin, @yvasyliev, update to v3.0.9+td.1.8.14, I fixed another similar windows-related bug
