### ISSUE TITLE
Where can i find version for jdk8?

### ISSUE THREAD

**Issue by ljs000225** [tdlight-team/tdlight-java#46]
I have an issue by using JDK 8 to latest versions.

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: it/tdlight/common/utils/CantLoadLibrary has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:650)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:632)

Process finished with exit code 1

```

how can i fix it? i assume that issue came because of the latest version of TDLight only supports JDK >= 11
But i can't find fit version of Tdligt from anywhere...

**Comment by Cavallium** [comment]
It should work on java 8. Probably I released the artifacts using java 11 by mistake. Tomorrow I'll fix this.

**Comment by ljs000225** [comment]
> It should work on java 8. Probably I released the artifacts using java 11 by mistake. Tomorrow I'll fix this.

It still throws me the same error :(

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: it/tdlight/common/utils/CantLoadLibrary has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

I'm on 1.7.65 of tdlight-java and 3.3.74 of td-lib-natives-windows-amd64

Maybe you just forgot about me ;(

**Comment by Cavallium** [comment]
I'm working on it now

**Comment by ljs000225** [comment]
> I'm working on it now

Just let me know when you release it..

**Comment by Cavallium** [comment]
Done, please upgrade to the latest version

**Comment by ljs000225** [comment]
LOL. not fixed. 
I'll do it by my self.

**Comment by MarcoBuster** [comment]
> LOL. not fixed. 
> I'll do it by my self.
> 

Lol

**Comment by Cavallium** [comment]
Fixed, finally

**Comment by Cavallium** [comment]
This version is released as a multi-release jar

**Comment by ljs000225** [comment]
> This version is released as a multi-release jar

I'm countin' on you for the last time..hope it works this time.............

**Comment by ljs000225** [comment]
> This version is released as a multi-release jar

It works fine now! thank you and sorry for bothering you 👍
